001/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/tasks');
Route::resource('tasks', 'TaskController');

001/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

001/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

001/app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TaskController extends Controller
{
    public function index() {
        $tasks = DB::select('SELECT id, content FROM tasks');
        return view('tasks.index')->with( 'tasks', $tasks );
    }

    public function store(Request $request) {
        $request->validate([
            'new-task' => 'required'
        ]);

        DB::transaction(function () use ($request) {
            DB::insert('INSERT INTO tasks (content, created_at, updated_at) VALUES ( ?, ?, ? )',
                [ $request->input('new-task'), now(), now() ]);
        });

        return redirect()->route('tasks.index');
    }

    public function edit($id) {
        $result = DB::select('SELECT id, content FROM tasks WHERE id = ?', [ $id ]);
        return view('tasks.edit')->with('task', $result[0]);
    }

    public function update(Request $request, $id) {
        $request->validate([
            'update-task' => 'required'
        ]);

        DB::transaction(function () use ($request, $id) {
            DB::update('UPDATE tasks SET content = ?, updated_at = ? WHERE id = ?', [
                $request->input('update-task'), now(), $id
            ]);
        });

        return redirect()->route('tasks.index');
    }

    public function destroy($id) {
        DB::transaction(function () use ($id) {
            DB::delete('DELETE FROM tasks WHERE id = ?', [ $id ]);
        });

        return redirect()-> route('tasks.index');
    }
}

001/resources/views/tasks/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>001 待辦事項清單</title>
</head>
<body>
    @if($errors->any())
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
    @endif

    <form method="post" action="{{ route('tasks.update', [ 'task' => $task->id ]) }}">
        @csrf
        @method('PUT')

        <label>
            <input type="text" name="update-task" value="{{ $task->content }}" autofocus>
            <button type="submit">儲存</button>
        </label>
    </form>

    <p>
        <a href="{{ route('tasks.index') }}">回到事項清單</a>
    </p>
</body>
</html>

001/resources/views/tasks/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>001 待辦事項清單</title>
</head>
<body>
    <h1>待辦事項清單</h1>

    @if ($errors->any())
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif

    <form method="post" action="{{ route('tasks.store') }}">
        @csrf
        <label>
            <input type="text" name="new-task" autofocus>
            <button type="submit">新增</button>
        </label>
    </form>

    <ul>
    @foreach ($tasks as $task)
        <li>
            {{ $task->content }} |
            <a href="{{ route('tasks.edit', [ 'task' => $task->id ]) }}">修改</a> |
            <a href="#delete">刪除</a>

            <form method="post" action="{{ route('tasks.destroy', [ 'task' => $task->id ]) }}">
                @csrf
                @method('DELETE')
            </form>

        </li>
    @endforeach
    </ul>

</body>
    <script>
        document.querySelectorAll('a[href="#delete"]').forEach(function(element) {
            element.addEventListener('click', function(event) {
                if(confirm('刪除事項 ?') == true) {
                    event.preventDefault();
                    // <a> 的下一個元素即爲要送出的 <form>
                    event.target.nextElementSibling.submit();
                }
            });
        });
    </script>
</html>